# Generated by Django 5.2 on 2025-12-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='movies.movie'),
        ),
    ]
