# Generated by Django 5.2 on 2025-12-22 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_favorite_movies'),
        ('accounts', '0002_user_profile_fields'),
    ]

    operations = [
    ]
