# Generated by Django 5.2 on 2025-12-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='catchphrase',
            field=models.TextField(blank=True),
        ),
    ]
