# Generated by Django 5.2 on 2025-12-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_boardpost_comment_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
